"""empty message

Revision ID: 000d7736611d
Revises: 30e993f53188
Create Date: 2024-05-13 23:33:55.135312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000d7736611d'
down_revision = '30e993f53188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('posts')
        batch_op.drop_column('alerts')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alerts', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('posts', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
