"""empty message

Revision ID: 11239a218bcb
Revises: 267b18613d05
Create Date: 2024-03-14 13:07:03.868795

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '11239a218bcb'
down_revision = '267b18613d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal', schema=None) as batch_op:
        batch_op.alter_column('original_price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('offer_price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.drop_column('date_of_creation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_creation', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.alter_column('offer_price',
               existing_type=sa.String(),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.alter_column('original_price',
               existing_type=sa.String(),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    # ### end Alembic commands ###
