"""empty message

Revision ID: 3bc1fea07b8e
Revises: a81ee315abec
Create Date: 2024-03-14 17:22:47.569148

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3bc1fea07b8e'
down_revision = 'a81ee315abec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal', schema=None) as batch_op:
        batch_op.alter_column('platform',
               existing_type=postgresql.ENUM('PC', 'Xbox', 'PS5', 'Nintendo', name='Platform_options'),
               type_=sa.String(length=250),
               existing_nullable=False)
        batch_op.alter_column('format',
               existing_type=postgresql.ENUM('Digital', 'CD', name='Format_options'),
               type_=sa.String(length=250),
               existing_nullable=False)
        batch_op.alter_column('item_type',
               existing_type=postgresql.ENUM('opcion1', 'opcion2', 'opcion3', 'opcion4', 'opcion5', name='Type_options'),
               type_=sa.String(length=250),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal', schema=None) as batch_op:
        batch_op.alter_column('item_type',
               existing_type=sa.String(length=250),
               type_=postgresql.ENUM('opcion1', 'opcion2', 'opcion3', 'opcion4', 'opcion5', name='Type_options'),
               existing_nullable=False)
        batch_op.alter_column('format',
               existing_type=sa.String(length=250),
               type_=postgresql.ENUM('Digital', 'CD', name='Format_options'),
               existing_nullable=False)
        batch_op.alter_column('platform',
               existing_type=sa.String(length=250),
               type_=postgresql.ENUM('PC', 'Xbox', 'PS5', 'Nintendo', name='Platform_options'),
               existing_nullable=False)

    # ### end Alembic commands ###
