"""empty message

Revision ID: a81ee315abec
Revises: 11239a218bcb
Create Date: 2024-03-14 15:12:34.779149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a81ee315abec'
down_revision = '11239a218bcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('interests')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interests', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
