"""empty message

Revision ID: f3f2122e3d4a
Revises: 
Create Date: 2024-03-07 23:56:41.186594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3f2122e3d4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('steam_profile', sa.String(length=40), nullable=True),
    sa.Column('twitch_profile', sa.String(length=40), nullable=True),
    sa.Column('posts', sa.String(), nullable=True),
    sa.Column('newsletter', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('deal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_title', sa.String(length=200), nullable=False),
    sa.Column('platform', sa.Enum('PC', 'Xbox', 'PS5', 'Nintendo', name='Platform_options'), nullable=False),
    sa.Column('date_of_creation', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('original_price', sa.Float(), nullable=False),
    sa.Column('offer_price', sa.Float(), nullable=False),
    sa.Column('format', sa.Enum('Digital', 'CD', name='Format_options'), nullable=False),
    sa.Column('item_type', sa.Enum('opcion1', 'opcion2', 'opcion3', 'opcion4', 'opcion5', name='Type_options'), nullable=False),
    sa.Column('promo_code', sa.String(length=250), nullable=True),
    sa.Column('scheduled', sa.Boolean(), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('img_url', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('interest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('upvote', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    op.drop_table('saved')
    op.drop_table('interest')
    op.drop_table('deal')
    op.drop_table('user')
    # ### end Alembic commands ###
