"""empty message

Revision ID: f3f2122e3d4a
Revises: 
Create Date: 2024-03-15 02:05:00.789417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3f2122e3d4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('steam_username', sa.String(length=40), nullable=True),
    sa.Column('twitch_username', sa.String(length=40), nullable=True),
    sa.Column('posts', sa.String(), nullable=True),
    sa.Column('alerts', sa.String(), nullable=True),
    sa.Column('newsletter', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('deal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_title', sa.String(length=200), nullable=False),
    sa.Column('platform', sa.String(length=250), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('original_price', sa.String(), nullable=False),
    sa.Column('offer_price', sa.String(), nullable=False),
    sa.Column('format', sa.String(length=250), nullable=False),
    sa.Column('item_type', sa.String(length=250), nullable=False),
    sa.Column('promo_code', sa.String(length=250), nullable=True),
    sa.Column('scheduled', sa.Boolean(), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(), nullable=True),
    sa.Column('offer_link', sa.String(length=200), nullable=False),
    sa.Column('image_url', sa.String(length=200), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('game_tags', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offer_link')
    )
    op.create_table('interest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    op.drop_table('saved')
    op.drop_table('interest')
    op.drop_table('deal')
    op.drop_table('user')
    # ### end Alembic commands ###
